"""Add species field to Pet model

Revision ID: 00fffe5aabfe
Revises: 432c17927f1a
Create Date: 2025-07-18 01:00:20.500351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00fffe5aabfe'
down_revision = '432c17927f1a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet', sa.Column('species', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pet', 'species')
    # ### end Alembic commands ###
