"""add missing fields to pricing_plans table

Revision ID: 22cb62fd5df0
Revises: aa64826264b8
Create Date: 2025-07-11 20:15:00.132710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22cb62fd5df0'
down_revision = 'aa64826264b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pricing_plans', sa.Column('max_pets', sa.Integer(), nullable=True))
    op.add_column('pricing_plans', sa.Column('requires_approval', sa.Boolean(), nullable=True))
    op.add_column('pricing_plans', sa.Column('is_featured', sa.Boolean(), nullable=True))
    op.add_column('pricing_plans', sa.Column('show_on_homepage', sa.Boolean(), nullable=True))
    op.add_column('pricing_plans', sa.Column('sort_order', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'role', ['name'])
    op.add_column('subscription', sa.Column('auto_renew', sa.Boolean(), nullable=True))
    op.add_column('subscription', sa.Column('cancellation_requested', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'cancellation_requested')
    op.drop_column('subscription', 'auto_renew')
    op.drop_constraint(None, 'role', type_='unique')
    op.drop_column('pricing_plans', 'sort_order')
    op.drop_column('pricing_plans', 'show_on_homepage')
    op.drop_column('pricing_plans', 'is_featured')
    op.drop_column('pricing_plans', 'requires_approval')
    op.drop_column('pricing_plans', 'max_pets')
    # ### end Alembic commands ###
