"""Add partner_subscription_id to payments table

Revision ID: 333b72c3fe5e
Revises: 3f8c7b6a5d92
Create Date: 2025-07-16 00:25:54.057484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '333b72c3fe5e'
down_revision = '3f8c7b6a5d92'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('partner_subscription_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'payments', 'partner_subscription', ['partner_subscription_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'partner_subscription_id')
    # ### end Alembic commands ###
