"""Add category and required_inputs to email templates

Revision ID: 432c17927f1a
Revises: 333b72c3fe5e
Create Date: 2025-07-16 23:13:50.404703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '432c17927f1a'
down_revision = '333b72c3fe5e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_templates', sa.Column('category', sa.String(length=50), nullable=False))
    op.add_column('email_templates', sa.Column('required_inputs', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_templates', 'required_inputs')
    op.drop_column('email_templates', 'category')
    # ### end Alembic commands ###
