"""Add subscription_id field to email_queue for regular subscriptions

Revision ID: 5ea905b954fd
Revises: 22080ffbc80c
Create Date: 2025-07-20 09:31:32.891298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ea905b954fd'
down_revision = '22080ffbc80c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_queue', sa.Column('subscription_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'email_queue', 'subscription', ['subscription_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'email_queue', type_='foreignkey')
    op.drop_column('email_queue', 'subscription_id')
    # ### end Alembic commands ###
