"""Add renewal retry tracking fields to subscription models

Revision ID: 89836cbf1bdf
Revises: 5ea905b954fd
Create Date: 2025-07-20 15:55:53.723899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89836cbf1bdf'
down_revision = '5ea905b954fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partner_subscription', sa.Column('renewal_attempts', sa.Integer(), nullable=True))
    op.add_column('partner_subscription', sa.Column('last_renewal_attempt', sa.DateTime(), nullable=True))
    op.add_column('partner_subscription', sa.Column('renewal_failure_reason', sa.String(length=500), nullable=True))
    op.add_column('subscription', sa.Column('renewal_attempts', sa.Integer(), nullable=True))
    op.add_column('subscription', sa.Column('last_renewal_attempt', sa.DateTime(), nullable=True))
    op.add_column('subscription', sa.Column('renewal_failure_reason', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'renewal_failure_reason')
    op.drop_column('subscription', 'last_renewal_attempt')
    op.drop_column('subscription', 'renewal_attempts')
    op.drop_column('partner_subscription', 'renewal_failure_reason')
    op.drop_column('partner_subscription', 'last_renewal_attempt')
    op.drop_column('partner_subscription', 'renewal_attempts')
    # ### end Alembic commands ###
