"""add reply_to field to email_queue table

Revision ID: 9f8e7d6c5b4a
Revises: 8db23a4bc700
Create Date: 2025-07-19 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f8e7d6c5b4a'
down_revision = '8db23a4bc700'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_queue', sa.Column('reply_to', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_queue', 'reply_to')
    # ### end Alembic commands ###
