"""Add PreStagePartner model for automatic role assignment

Revision ID: a090fa1aaece
Revises: 89836cbf1bdf
Create Date: 2025-07-20 15:49:10.437669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a090fa1aaece'
down_revision = '89836cbf1bdf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pre_stage_partner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=120), nullable=False),
    sa.Column('owner_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pre_stage_partner_email'), 'pre_stage_partner', ['email'], unique=True)
    op.create_foreign_key(None, 'email_queue', 'subscription', ['subscription_id'], ['id'])
    op.add_column('partner_subscription', sa.Column('renewal_attempts', sa.Integer(), nullable=True))
    op.add_column('partner_subscription', sa.Column('last_renewal_attempt', sa.DateTime(), nullable=True))
    op.add_column('partner_subscription', sa.Column('renewal_failure_reason', sa.String(length=500), nullable=True))
    op.add_column('subscription', sa.Column('renewal_attempts', sa.Integer(), nullable=True))
    op.add_column('subscription', sa.Column('last_renewal_attempt', sa.DateTime(), nullable=True))
    op.add_column('subscription', sa.Column('renewal_failure_reason', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'renewal_failure_reason')
    op.drop_column('subscription', 'last_renewal_attempt')
    op.drop_column('subscription', 'renewal_attempts')
    op.drop_column('partner_subscription', 'renewal_failure_reason')
    op.drop_column('partner_subscription', 'last_renewal_attempt')
    op.drop_column('partner_subscription', 'renewal_attempts')
    op.drop_constraint(None, 'email_queue', type_='foreignkey')
    op.drop_index(op.f('ix_pre_stage_partner_email'), table_name='pre_stage_partner')
    op.drop_table('pre_stage_partner')
    # ### end Alembic commands ###
