"""add missing fields to email_queue table

Revision ID: a1b2c3d4e5f6
Revises: 9f8e7d6c5b4a
Create Date: 2025-07-19 01:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '9f8e7d6c5b4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add email_type column
    op.add_column('email_queue', sa.Column('email_type', sa.String(length=50), nullable=True))
    
    # Add email_metadata column (JSON)
    op.add_column('email_queue', sa.Column('email_metadata', sa.JSON(), nullable=True))
    
    # Add template_id foreign key
    op.add_column('email_queue', sa.Column('template_id', sa.Integer(), nullable=True))
    
    # Add user_id foreign key
    op.add_column('email_queue', sa.Column('user_id', sa.Integer(), nullable=True))
    
    # Add partner_subscription_id foreign key
    op.add_column('email_queue', sa.Column('partner_subscription_id', sa.Integer(), nullable=True))
    
    # Add error tracking fields
    op.add_column('email_queue', sa.Column('last_error', sa.Text(), nullable=True))
    op.add_column('email_queue', sa.Column('error_history', sa.JSON(), nullable=True))
    
    # Add foreign key constraints
    try:
        op.create_foreign_key('fk_email_queue_template_id', 'email_queue', 'email_templates', ['template_id'], ['id'])
    except:
        pass  # Foreign key might already exist or table might not exist
        
    try:
        op.create_foreign_key('fk_email_queue_user_id', 'email_queue', 'user', ['user_id'], ['id'])
    except:
        pass  # Foreign key might already exist or table might not exist
        
    try:
        op.create_foreign_key('fk_email_queue_partner_subscription_id', 'email_queue', 'partner_subscription', ['partner_subscription_id'], ['id'])
    except:
        pass  # Foreign key might already exist or table might not exist

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop foreign key constraints
    try:
        op.drop_constraint('fk_email_queue_partner_subscription_id', 'email_queue', type_='foreignkey')
    except:
        pass
        
    try:
        op.drop_constraint('fk_email_queue_user_id', 'email_queue', type_='foreignkey')
    except:
        pass
        
    try:
        op.drop_constraint('fk_email_queue_template_id', 'email_queue', type_='foreignkey')
    except:
        pass
    
    # Drop columns
    op.drop_column('email_queue', 'error_history')
    op.drop_column('email_queue', 'last_error')
    op.drop_column('email_queue', 'partner_subscription_id')
    op.drop_column('email_queue', 'user_id')
    op.drop_column('email_queue', 'template_id')
    op.drop_column('email_queue', 'email_metadata')
    op.drop_column('email_queue', 'email_type')

    # ### end Alembic commands ###
