"""create payment gateway pricing plan and payment tables

Revision ID: effcb230d5db
Revises: 5fa12849d5ff
Create Date: 2025-07-11 18:40:28.387258

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'effcb230d5db'
down_revision = '5fa12849d5ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_gateways',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('secret_key', sa.Text(), nullable=True),
    sa.Column('publishable_key', sa.Text(), nullable=True),
    sa.Column('client_id', sa.Text(), nullable=True),
    sa.Column('webhook_secret', sa.Text(), nullable=True),
    sa.Column('environment', sa.String(length=20), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pricing_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('billing_period', sa.String(length=20), nullable=False),
    sa.Column('plan_type', sa.String(length=20), nullable=False),
    sa.Column('max_tags', sa.Integer(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('payment_gateway', sa.String(length=50), nullable=False),
    sa.Column('payment_intent_id', sa.String(length=200), nullable=True),
    sa.Column('transaction_id', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_type', sa.String(length=50), nullable=False),
    sa.Column('payment_metadata', sa.JSON(), nullable=True),
    sa.Column('gateway_response', sa.JSON(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Drop foreign key constraint before dropping table
    op.drop_constraint('subscription_ibfk_3', 'subscription', type_='foreignkey')
    op.drop_table('pricing_plan')
    op.drop_table('payment_gateway')
    
    # Add new columns and constraints
    op.create_unique_constraint(None, 'role', ['name'])
    op.add_column('subscription', sa.Column('auto_renew', sa.Boolean(), nullable=True))
    op.add_column('subscription', sa.Column('cancellation_requested', sa.Boolean(), nullable=True))
    op.create_foreign_key('subscription_ibfk_4', 'subscription', 'pricing_plans', ['pricing_plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('subscription_ibfk_4', 'subscription', type_='foreignkey')
    op.create_foreign_key('subscription_ibfk_3', 'subscription', 'pricing_plan', ['pricing_plan_id'], ['id'])
    op.drop_column('subscription', 'cancellation_requested')
    op.drop_column('subscription', 'auto_renew')
    op.drop_constraint(None, 'role', type_='unique')
    
    # Recreate old tables
    op.create_table('payment_gateway',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('enabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('api_key', mysql.TEXT(), nullable=True),
    sa.Column('secret_key', mysql.TEXT(), nullable=True),
    sa.Column('webhook_secret', mysql.TEXT(), nullable=True),
    sa.Column('environment', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('publishable_key', mysql.TEXT(), nullable=True),
    sa.Column('client_id', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('pricing_plan',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('plan_type', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('currency', mysql.VARCHAR(length=3), nullable=True),
    sa.Column('billing_period', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('features', mysql.TEXT(), nullable=True),
    sa.Column('max_tags', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_pets', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('requires_approval', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('is_featured', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('show_on_homepage', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('sort_order', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    
    # Drop new tables
    op.drop_table('payments')
    op.drop_table('pricing_plans')
    op.drop_table('payment_gateways')
    # ### end Alembic commands ###
