name: Push LTFPQRR Web Service to Docker Hub (Beta)

concurrency:
  group: web-beta
  cancel-in-progress: true

on:
  push:
    branches: [beta]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: web-beta
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: harbor.vm.kumpeapps.com
          username: "robot_github"
          password: ${{ secrets.HARBOR_SECRET }}
          
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: harbor.vm.kumpeapps.com/kumpeapps-web/ltfpqrr-web-app
          tags: |
            type=raw,value=latest-beta
            
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64  # Beta: single platform for faster development builds
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1
